meta_title: "NetStarted the startup agency."
meta_description: "You have a idea, but you have no idea how to create it yourself?NetStarted is there.
Contact us, we will help you from idea to create a company."
meta_image: "banner.jpeg" # Une image dans votre dossier app/assets/images/
twitter_account: "@MikeNetStarted" # indispensable pour les Twitter Cards
